#General
# Read length: 49bp
strandedness: Unstranded

#featureCounts
ensembl_gtf: /gpfs/hpchome/a72094/rocket/annotations/GRCh38/Gencode_28/gencode.v28.basic.annotation.gtf

#HISAT2 config
hisat2_index: /gpfs/hpchome/a72094/rocket/annotations/GRCh38/hisat2_index_v90/Homo_sapiens.GRCh38.dna.primary_assembly
hisat2_flags: ""

#Splicing
leafcutter_root: "/gpfs/hpchome/a72094/software/leafcutter-0.2.7"

#Dictionary of sample names
samples:
  _EGAZ00001039787_EB_TWPID11743_F: [processed/_EGAZ00001039787_EB_TWPID11743_F_1.fastq.gz, processed/_EGAZ00001039787_EB_TWPID11743_F_2.fastq.gz]
