#!/bin/bash
# Rename multiple files

mv processed/GENCORD/hisat2_ss/UC018L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB018.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC019L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB019.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC024L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB024.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC025L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB025.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC042L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB042.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC048L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB048.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC049L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB049.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC050L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB050.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC051L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB051.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC060L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB060.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC062L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB062.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC078L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB078.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC086L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB086.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC087L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB087.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC088L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB088.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC093L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB093.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1001.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1001.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1007.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1007.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC100L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB100.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1010.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1010.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1011.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1011.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1012.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1012.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1014.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1014.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1016.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1016.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1021.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1021.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1023.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1023.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1024.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1024.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1025.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1025.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1027.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1027.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1028.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1028.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1029.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1029.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1030.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1030.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC103L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB103.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1040.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1040.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1045.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1045.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1046.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1046.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1047.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1047.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1048.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1048.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1052.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1052.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1053.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1053.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1055.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1055.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1056.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1056.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1057.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1057.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1058.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1058.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1059.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1059.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC105L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB105.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1061.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1061.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1062.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1062.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1064.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1064.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1067.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1067.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1068.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1068.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1069.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1069.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1070.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1070.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1071.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1071.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1072.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1072.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1073.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1073.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1074.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1074.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1075.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1075.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1076.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1076.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1077.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1077.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1078.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1078.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1079.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1079.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1080.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1080.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1083.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1083.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1085.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1085.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1086.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1086.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1087.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1087.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1088.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1088.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1089.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1089.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC108L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB108.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1090.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1090.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1091.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1091.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1092.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1092.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1094.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1094.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1096.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1096.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1097.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1097.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1098.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1098.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1099.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1099.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1100.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1100.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1101.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1101.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1102.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1102.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1103.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1103.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1104.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1104.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1105.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1105.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1106.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1106.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1107.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1107.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1108.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1108.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1109.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1109.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC110L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB110.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1112.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1112.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1113.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1113.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1115.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1115.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1116.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1116.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1117.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1117.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1119.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1119.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1120.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1120.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1123.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1123.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1124.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1124.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1125.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1125.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1126.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1126.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1128.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1128.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1129.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1129.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1130.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1130.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1131.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1131.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1135.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1135.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1136.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1136.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1137.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1137.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1139.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1139.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC113L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB113.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1143.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1143.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1146.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1146.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1148.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1148.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC114L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB114.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1156.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1156.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1159.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1159.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC115L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB115.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1160.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1160.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1161.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1161.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1163.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1163.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1164.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1164.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1167.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1167.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1168.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1168.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1169.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1169.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC116L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB116.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1170.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1170.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1171.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1171.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1174.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1174.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1175.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1175.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1176.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1176.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1178.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1178.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1179.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1179.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC117L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB117.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1180.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1180.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1181.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1181.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1182.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1182.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1183.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1183.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1184.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1184.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1185.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1185.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1186.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1186.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1187.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1187.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1188.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1188.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1189.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1189.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1190.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1190.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1191.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1191.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1192.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1192.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1193.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1193.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1194.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1194.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1195.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1195.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1196.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1196.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1198.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1198.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1199.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1199.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1200.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1200.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1201.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1201.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1203.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1203.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1205.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1205.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1206.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1206.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1207.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1207.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1208.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1208.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1210.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1210.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1211.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1211.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1212.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1212.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1215.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1215.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1216.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1216.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1217.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1217.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCB1218.splice_sites.txt processed/GENCORD/hisat2_ss/UCB1218.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC122L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB122.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC124L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB124.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC125L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB125.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC130L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB130.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC137L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB137.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC139L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB139.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC141L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB141.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC144L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB144.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC152L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB152.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC164L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB164.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC167L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB167.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC169L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB169.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC177L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB177.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC181L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB181.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC183L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB183.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC188L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB188.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC223L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB223.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC225L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB225.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC226L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB226.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC227L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB227.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC251L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB251.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC253L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB253.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC255L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB255.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC277L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB277.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC282L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB282.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC285L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB285.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC304L.splice_sites.txt processed/GENCORD/hisat2_ss/UCB304.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC018F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF018.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC025F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF025.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC034F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF034.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC042F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF042.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC048F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF048.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC049F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF049.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC050F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF050.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC051F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF051.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC060F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF060.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC062F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF062.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC078F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF078.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC079F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF079.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC086F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF086.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC088F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF088.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC093F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF093.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1001.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1001.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1007.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1007.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC100F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF100.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1010.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1010.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1011.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1011.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1012.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1012.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1013.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1013.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1014.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1014.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1016.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1016.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1021.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1021.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1023.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1023.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1024.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1024.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1025.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1025.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1027.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1027.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1028.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1028.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1029.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1029.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1030.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1030.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC103F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF103.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1040.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1040.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1045.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1045.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1046.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1046.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1047.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1047.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1048.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1048.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1052.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1052.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1053.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1053.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1055.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1055.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1056.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1056.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1057.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1057.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1058.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1058.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1059.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1059.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC105F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF105.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1061.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1061.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1062.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1062.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1064.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1064.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1067.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1067.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1068.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1068.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1069.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1069.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1070.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1070.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1071.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1071.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1072.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1072.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1073.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1073.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1074.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1074.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1075.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1075.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1076.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1076.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1077.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1077.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1078.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1078.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1079.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1079.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1080.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1080.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1083.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1083.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1085.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1085.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1086.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1086.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1087.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1087.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1088.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1088.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1089.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1089.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC108F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF108.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1090.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1090.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1091.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1091.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1092.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1092.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1094.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1094.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1096.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1096.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1097.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1097.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1098.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1098.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1099.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1099.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1100.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1100.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1101.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1101.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1102.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1102.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1103.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1103.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1104.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1104.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1105.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1105.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1106.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1106.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1107.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1107.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1108.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1108.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1109.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1109.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC110F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF110.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1112.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1112.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1113.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1113.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1115.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1115.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1116.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1116.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1117.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1117.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1119.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1119.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1120.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1120.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1123.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1123.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1124.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1124.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1125.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1125.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1126.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1126.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1128.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1128.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1129.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1129.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1130.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1130.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1131.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1131.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1135.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1135.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1136.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1136.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1137.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1137.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1139.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1139.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC113F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF113.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1143.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1143.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1146.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1146.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1148.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1148.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC114F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF114.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1156.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1156.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1159.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1159.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC115F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF115.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1160.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1160.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1161.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1161.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1163.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1163.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1164.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1164.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1167.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1167.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1168.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1168.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1169.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1169.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC116F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF116.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1170.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1170.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1171.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1171.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1174.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1174.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1175.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1175.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1176.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1176.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1178.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1178.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1179.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1179.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC117F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF117.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1180.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1180.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1181.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1181.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1182.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1182.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1183.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1183.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1184.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1184.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1185.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1185.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1186.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1186.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1187.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1187.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1188.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1188.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1189.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1189.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1190.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1190.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1191.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1191.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1192.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1192.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1193.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1193.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1194.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1194.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1195.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1195.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1196.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1196.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1198.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1198.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1199.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1199.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1200.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1200.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1201.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1201.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1203.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1203.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1205.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1205.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1206.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1206.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1207.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1207.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1208.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1208.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1210.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1210.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1211.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1211.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1212.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1212.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1215.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1215.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1216.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1216.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1217.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1217.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCF1218.splice_sites.txt processed/GENCORD/hisat2_ss/UCF1218.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC122F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF122.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC124F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF124.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC130F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF130.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC137F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF137.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC139F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF139.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC144F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF144.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC152F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF152.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC164F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF164.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC167F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF167.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC169F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF169.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC177F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF177.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC181F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF181.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC183F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF183.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC188F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF188.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC223F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF223.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC226F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF226.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC227F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF227.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC251F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF251.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC253F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF253.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC255F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF255.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC277F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF277.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC282F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF282.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC285F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF285.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC304F.splice_sites.txt processed/GENCORD/hisat2_ss/UCF304.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC018T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT018.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC019T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT019.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC024T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT024.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC025T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT025.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC034T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT034.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC042T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT042.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC048T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT048.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC049T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT049.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC050T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT050.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC051T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT051.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC060T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT060.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC078T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT078.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC079T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT079.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC087T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT087.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC088T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT088.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC093T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT093.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1001.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1001.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1007.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1007.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC100T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT100.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1010.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1010.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1011.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1011.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1012.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1012.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1013.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1013.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1014.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1014.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1016.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1016.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1021.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1021.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1023.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1023.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1024.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1024.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1025.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1025.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1027.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1027.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1028.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1028.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1029.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1029.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1030.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1030.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC103T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT103.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1040.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1040.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1045.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1045.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1046.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1046.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1047.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1047.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1048.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1048.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1052.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1052.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1053.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1053.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1055.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1055.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1056.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1056.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1057.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1057.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1058.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1058.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1059.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1059.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC105T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT105.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1061.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1061.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1062.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1062.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1064.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1064.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1067.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1067.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1068.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1068.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1069.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1069.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1070.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1070.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1071.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1071.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1072.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1072.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1073.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1073.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1074.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1074.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1075.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1075.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1076.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1076.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1077.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1077.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1078.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1078.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1079.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1079.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1080.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1080.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1083.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1083.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1086.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1086.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1087.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1087.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1088.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1088.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1089.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1089.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1090.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1090.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1091.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1091.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1092.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1092.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1094.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1094.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1096.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1096.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1097.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1097.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1098.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1098.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1099.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1099.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1100.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1100.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1101.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1101.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1102.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1102.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1103.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1103.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1104.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1104.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1105.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1105.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1106.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1106.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1107.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1107.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1108.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1108.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1109.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1109.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC110T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT110.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1112.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1112.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1113.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1113.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1115.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1115.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1116.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1116.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1117.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1117.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1119.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1119.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1120.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1120.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1123.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1123.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1124.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1124.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1125.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1125.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1126.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1126.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1128.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1128.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1129.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1129.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1130.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1130.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1131.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1131.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1135.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1135.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1136.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1136.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1137.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1137.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1139.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1139.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC113T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT113.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1143.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1143.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1146.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1146.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1148.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1148.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC114T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT114.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1156.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1156.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1159.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1159.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1160.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1160.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1161.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1161.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1163.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1163.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1164.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1164.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1167.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1167.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1168.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1168.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1169.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1169.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1170.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1170.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1171.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1171.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1174.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1174.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1175.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1175.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1176.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1176.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1178.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1178.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1179.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1179.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC117T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT117.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1180.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1180.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1181.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1181.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1182.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1182.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1183.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1183.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1184.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1184.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1185.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1185.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1186.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1186.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1188.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1188.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1189.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1189.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1190.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1190.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1191.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1191.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1192.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1192.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1193.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1193.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1194.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1194.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1195.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1195.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1196.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1196.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1198.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1198.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1199.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1199.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1200.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1200.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1201.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1201.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1203.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1203.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1205.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1205.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1206.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1206.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1207.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1207.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1208.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1208.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1210.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1210.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1211.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1211.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1212.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1212.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1215.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1215.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1216.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1216.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1217.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1217.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UCT1218.splice_sites.txt processed/GENCORD/hisat2_ss/UCT1218.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC122T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT122.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC124T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT124.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC125T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT125.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC130T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT130.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC137T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT137.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC139T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT139.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC141T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT141.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC144T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT144.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC152T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT152.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC164T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT164.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC167T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT167.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC169T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT169.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC177T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT177.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC181T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT181.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC183T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT183.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC188T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT188.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC223T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT223.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC226T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT226.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC227T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT227.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC251T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT251.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC253T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT253.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC255T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT255.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC277T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT277.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC282T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT282.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC285T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT285.splice_sites.txt
mv processed/GENCORD/hisat2_ss/UC304T.splice_sites.txt processed/GENCORD/hisat2_ss/UCT304.splice_sites.txt
